#!/bin/bash

if [ ! -z "$MARATHON_APP_ID" ]; then

    if [ -f /dev/shm/kibana-catalog-env ]; then
        source /dev/shm/kibana-catalog-env
    elif [ -f /dev/shm/kibana-spandex-env ]; then
        source /dev/shm/kibana-spandex-env
    else
        echo "-----------------------------"
        echo "ERROR: no clortho file found!"
        echo "-----------------------------"
    fi

fi

set -ev

if [ ! -z "$MARATHON_APP_ID" ]; then
    . /bin/set_ark_host
    /bin/env_parse /etc/service/kibana/config/${CONFIG}.j2
else
    echo "" > /etc/service/kibana/config/${CONFIG}
    rm /etc/service/kibana/config/${CONFIG}.j2
fi

exec su socrata -c "/etc/service/kibana/bin/kibana"
